services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
      POSTGRES_DB: jira
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
